[package]
name = "readyset-sql-parsing"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
clap = { workspace = true }
nom-sql = { path = "../nom-sql" }
paste = { workspace = true }
pretty_assertions = { workspace = true }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
sqlparser = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }


[lints]
workspace = true
