[package]
name = "readyset-e2e-tests"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dev-dependencies]
chrono = { workspace = true }
dataflow-state = { path = "../dataflow-state" }
futures = { workspace = true }
itertools = { workspace = true }
mysql_async = { workspace = true }
mysql_common = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client-test-helpers = { path = "../readyset-client-test-helpers", features = [
    "mysql",
    "postgres",
] }
readyset-tracing = { path = "../readyset-tracing" }
readyset-sql = { path = "../readyset-sql" }
readyset-util = { path = "../readyset-util" }
serial_test = { workspace = true }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }
tokio = { workspace = true, features = ["full"] }

[features]
utf8mb4_all_codepoints_test = []

[lints.clippy]
dbg_macro = "warn"
# In a test crate, we are ok with todo!(); could remove them and just use workspace lints
todo = "allow"
