[package]
name = "readyset-tracing"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true }

tracing = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = { workspace = true, features = ["semconv_experimental"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing-appender = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }

[dev-dependencies]
tracing-attributes = { workspace = true }

[lints]
workspace = true
